server {
    listen 80;
    server_name @DOMAIN@;
    return 301 https://$host$request_uri;
    more_clear_headers Server;
    more_set_headers "X-Content-Type-Options: nosniff";
    if ($request_method !~ ^(GET|HEAD|POST|OPTIONS)$) { return 405; }
}

server {
    listen 443 ssl;
    server_name @DOMAIN@;
    ssl_certificate @SSL_CERT@;
    ssl_certificate_key @SSL_KEY@;
    more_clear_headers Server;
    more_set_headers "X-Content-Type-Options: nosniff";
    more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
    server_tokens off;
    client_max_body_size 55G;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias @APP_DIR@/staticfiles/;
        autoindex off;
        error_page 403 = @static_404;
        more_set_headers "X-Content-Type-Options: nosniff";
        more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
        more_set_headers "Cross-Origin-Resource-Policy: same-origin";
        more_set_headers "Cache-Control: public, max-age=2592000, immutable";
    }
    location @static_404 { return 404; }
    location / {
        limit_req zone=portability burst=20 nodelay;
        include proxy_params;
        proxy_pass http://unix:/run/portability/portability-server.sock;
        proxy_buffer_size 16k;
        proxy_buffers 4 16k;
        more_set_headers "Cache-Control: no-store, no-cache, must-revalidate";
    }
    if ($request_method !~ ^(GET|HEAD|POST)$) { return 405; }
}
