# Generated by Django 4.2 on 2026-03-20 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('researcher_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('processing_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_changed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('permission', models.CharField(choices=[('add_user', 'Add User'), ('read_data', 'Read Data')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
