# Generated by Django 4.2 on 2026-03-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('google_user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('oauth_state', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(choices=[('authorized', 'Authorized, waiting for download'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='authorized', max_length=20)),
                ('downloaded_files', models.JSONField(blank=True, default=list)),
                ('data_job_ids', models.JSONField(blank=True, default=dict)),
                ('job_status', models.JSONField(blank=True, default=dict, help_text="Maps job_id to {'completed': bool, 'downloaded_at': timestamp, 'state': job_state}")),
                ('file_status', models.JSONField(blank=True, default=dict, help_text="Maps filepath to {'processed': bool, 'processed_at': timestamp}")),
                ('data_type_status', models.JSONField(blank=True, default=dict, help_text="Maps data_type to {'received': bool, 'received_at': timestamp}")),
            ],
            bases=('donations.donation',),
        ),
    ]
