# Generated by Django 4.2 on 2026-03-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_googledonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('tiktok_user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('code_verifier', models.CharField(blank=True, max_length=200)),
                ('oauth_state', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(choices=[('authorized', 'Authorized, waiting for data'), ('data_requested', 'Data portability request submitted'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='authorized', max_length=20)),
            ],
            bases=('donations.donation',),
        ),
    ]
