# Generated by Django 4.2 on 2026-03-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_tiktokdonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='researcher_token',
        ),
        migrations.RemoveField(
            model_name='researchertoken',
            name='permission',
        ),
        migrations.AddField(
            model_name='donation',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.researchertoken'),
        ),
    ]
