# Generated by Django 4.2 on 2026-03-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_remove_donation_researcher_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='data_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='data_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
