# Generated by Django 4.2 on 2026-03-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_assign_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='participant_token',
            new_name='token',
        ),
    ]
