# Generated by Django 4.2 on 2026-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_rename_participant_token_donation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
