# Generated by Django 4.2 on 2026-03-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_donation_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='requested_data_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
