# Generated by Django 4.2 on 2026-03-26 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_hash_researcher_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='suggested_participant_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
