# Generated by Django 5.2 on 2026-06-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_alter_tiktokdonation_tiktok_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokExportDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.donation')),
                ('uploaded_files', models.JSONField(blank=True, default=list)),
                ('file_status', models.JSONField(blank=True, default=dict, help_text="Maps filepath to {'processed': bool, 'processed_at': timestamp}")),
                ('data_type_status', models.JSONField(blank=True, default=dict, help_text="Maps data_type to {'received': bool, 'received_at': timestamp}")),
            ],
            bases=('donations.donation',),
        ),
    ]
