# Generated by Django 5.2 on 2026-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_tiktokexportdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokexportdonation',
            name='processing_status',
            field=models.CharField(choices=[('authorized', 'Authorized, waiting for upload'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='authorized', max_length=20),
        ),
    ]
