# Generated by Django 5.2.15 on 2026-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_tiktokexportdonation_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokexportdonation',
            name='processing_status',
            field=models.CharField(choices=[('waiting', 'Waiting for upload'), ('processing', 'Processing'), ('processed', 'Processed successfully'), ('error', 'Error during processing')], default='waiting', max_length=20),
        ),
    ]
