# Generated by Django 5.2.15 on 2026-09-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_alter_tiktokexportdonation_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='can_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='data_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
