# Generated by Django 5.2.15 on 2026-09-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_donation_can_delete_at_donation_data_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='processing_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
