# Generated by Django 5.2.15 on 2026-09-09 08:35, hand-edited.
from datetime import timedelta

import django.db.models.deletion
import donations.models
from django.db import migrations, models
from django.utils import timezone


def fill_expires_at(apps, schema_editor):
    """Give existing researcher tokens a one-year expiry from migration time."""
    ResearcherToken = apps.get_model('donations', 'ResearcherToken')
    ResearcherToken.objects.filter(expires_at__isnull=True).update(
        expires_at=timezone.now() + timedelta(days=365)
    )


def noop(apps, schema_editor):
    """Nothing to undo: the forward fill is a one-time backfill, not state."""


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0020_donation_processing_claimed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchertoken',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(fill_expires_at, noop),
        migrations.AlterField(
            model_name='researchertoken',
            name='expires_at',
            field=models.DateTimeField(default=donations.models.default_researcher_token_expiry),
        ),
        migrations.CreateModel(
            name='ResearcherSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='donations.researchertoken')),
            ],
        ),
    ]
