# Generated by Django 5.2.15 on 2026-09-10, hand-edited.
import json

from django.db import migrations, models

from donations.utils.crypto import encrypt_text


def encrypt_existing_user_info(apps, schema_editor):
    """Encrypt any existing plaintext user_info dicts into the new column."""
    TikTokDonation = apps.get_model('donations', 'TikTokDonation')
    for donation in TikTokDonation.objects.exclude(user_info={}):
        if not donation.user_info:
            continue
        donation.user_info_encrypted = encrypt_text(json.dumps(donation.user_info))
        donation.save(update_fields=['user_info_encrypted'])


def noop(apps, schema_editor):
    """Nothing to undo: dropping the plaintext column is the point."""


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0021_researcher_token_expiry_and_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokdonation',
            name='user_info_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(encrypt_existing_user_info, noop),
        migrations.RemoveField(
            model_name='tiktokdonation',
            name='user_info',
        ),
    ]
