# Generated by Django 5.2.15 on 2026-09-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0022_encrypt_tiktok_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='suggested_participant_token',
        ),
    ]
